# Generated by Django 5.2.17 on 2026-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_add_casa_sonata_preorder_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Casa Sonata', max_length=120)),
                ('tagline', models.CharField(default='Contemporary Italian kitchen', max_length=180)),
                ('hero_title', models.CharField(default='Every meal, a little sonata.', max_length=180)),
                ('hero_description', models.TextField(default='An intimate neighborhood table for seasonal cooking and the pleasure of staying awhile.')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/')),
                ('introduction_title', models.CharField(default='The kind of place you find yourself returning to.', max_length=180)),
                ('introduction', models.TextField(default='Casa Sonata brings the warmth of an Italian home to the heart of the city.')),
                ('about_title', models.CharField(default='Born from a love of feeding people well.', max_length=180)),
                ('about_story', models.TextField(default='Casa Sonata began with a simple dream: create the kind of restaurant that feels like the home of a dear friend with exceptional taste.')),
                ('address', models.TextField(default='18 Via del Teatro\n20121 Milano, Italy')),
                ('phone', models.CharField(default='+39 02 555 0199', max_length=60)),
                ('email', models.EmailField(default='ciao@casasonata.it', max_length=254)),
                ('opening_hours', models.TextField(default='Tuesday – Thursday: 5:30pm – 11pm\nFriday – Sunday: 5:30pm – 11:30pm\nMonday: Closed')),
                ('announcement', models.CharField(blank=True, max_length=240)),
                ('private_dining_text', models.TextField(default='For intimate celebrations, team dinners, and everything worth marking, our private dining room is yours.')),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, help_text='For example: Food, Interior, or Events', max_length=80),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
