# Generated by Django 5.2.17 on 2026-09-28 15:04

from django.db import migrations, models


def create_staff_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    DiningTable = apps.get_model("restaurant", "DiningTable")
    for name in ("Cashier", "Kitchen Staff", "Inventory Staff"):
        Group.objects.get_or_create(name=name)
    for number in range(1, 7):
        DiningTable.objects.get_or_create(name=f"Table {number}", defaults={"seats": 4, "active": True})


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_inventoryitem_stockmovement'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diningtable',
            options={'ordering': ['seats', 'name'], 'permissions': [('view_staff_tables', 'Can view table service status'), ('change_staff_tables', 'Can update table service status')]},
        ),
        migrations.AlterModelOptions(
            name='foodorder',
            options={'permissions': [('view_staff_orders', 'Can view food orders in staff interface'), ('change_staff_order_status', 'Can update food order status'), ('view_staff_payments', 'Can view customer payment details'), ('change_staff_payments', 'Can approve or reject customer payments'), ('view_staff_reports', 'Can view financial reports')]},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'reservation_time'], 'permissions': [('view_staff_reservations', 'Can view staff reservation details')]},
        ),
        migrations.AddField(
            model_name='diningtable',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_staff_roles, migrations.RunPython.noop),
        migrations.AddField(
            model_name='foodorder',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed')], default='new', max_length=12),
        ),
    ]
