# Generated by Django 5.2.17 on 2026-10-06 04:23

import django.db.models.deletion
from django.db import migrations, models


def create_default_ktv_rooms(apps, schema_editor):
    Room = apps.get_model('restaurant', 'KTVRoom')
    rooms = [
        ('Room A', 'Family Room', 15, 18, '249.00'),
        ('Room C', 'Family Room', 15, 18, '249.00'),
        ('Room D', 'Barkada Room', 5, 8, '149.00'),
    ]
    for name, room_type, minimum, maximum, price in rooms:
        Room.objects.get_or_create(
            name=name,
            defaults={
                'room_type': room_type,
                'min_capacity': minimum,
                'max_capacity': maximum,
                'hourly_price': price,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_expense_amount_alter_stockin_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KTVRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('room_type', models.CharField(max_length=40)),
                ('min_capacity', models.PositiveSmallIntegerField()),
                ('max_capacity', models.PositiveSmallIntegerField()),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=12)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('change_staff_ktv_room_status', 'Can update KTV room service status')],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ktv_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ktv_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.ktvroom'),
        ),
        migrations.RunPython(create_default_ktv_rooms, migrations.RunPython.noop),
    ]
