# Generated by Django 5.2.17 on 2026-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_reservation_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktvroom',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('completed', 'Completed')], default='available', max_length=12),
        ),
    ]
