# Generated by Django 5.2.17 on 2026-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_ktvroom_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(default='Casa Sonata', max_length=180)),
                ('category', models.CharField(choices=[('live_music', 'Live music'), ('acoustic', 'Acoustic night'), ('dining', 'Special dining night'), ('holiday', 'Holiday celebration'), ('ktv', 'KTV event'), ('promotion', 'Food promotion'), ('birthday', 'Birthday event'), ('private', 'Private gathering'), ('other', 'Other')], default='other', max_length=20)),
                ('additional_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('reservation_option', models.CharField(choices=[('none', 'No reservation link'), ('table', 'Dine-in table'), ('ktv', 'KTV room'), ('both', 'Table and KTV')], default='none', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date', 'start_time', 'title'],
            },
        ),
    ]
