# Generated by Django 5.2.17 on 2026-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='General', max_length=80),
        ),
        migrations.AddField(
            model_name='ktvroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ktvroom',
            name='image',
            field=models.ImageField(blank=True, upload_to='ktv_rooms/'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='ktvroom',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('completed', 'Completed'), ('maintenance', 'Maintenance')], default='available', max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
    ]
