# Generated by Django 5.2.17 on 2026-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_foodorder_payment_proof_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='cash_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
