# Generated by Django 5.2.17 on 2026-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_foodorder_cash_change_foodorder_cash_received_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'reservation_time'], 'permissions': [('view_staff_reservations', 'Can view staff reservation details'), ('change_staff_reservations', 'Can update staff reservation status')]},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('confirmed', 'Reserved'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
    ]
