# Generated by Django 5.2.18 on 2026-10-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_dashboardnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-In')], default='online', max_length=8),
        ),
    ]
