# Generated by Django 5.2.18 on 2026-10-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_reservation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='gcash_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='gcash_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='gcash_qr_code',
            field=models.ImageField(blank=True, upload_to='payments/'),
        ),
    ]
